name: Publish Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-artifact.yml

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: LS
        run: ls -R

      - name: Archive artifact
        run: |
          zip -r "DtD.zip" "DtD"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: DtD.zip
